# Generated by Django 5.2.5 on 2025-08-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groupdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdata',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
