# Generated by Django 5.2.5 on 2025-08-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_groupdata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdata',
            name='independent_variable',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='SubjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_data', to='core.groupdata')),
            ],
        ),
    ]
