# Generated by Django 5.2.5 on 2025-08-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subject_delete_subjectdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='groupdata',
            name='label',
        ),
        migrations.RemoveField(
            model_name='groupdata',
            name='value',
        ),
        migrations.CreateModel(
            name='GroupSubData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('label', models.TextField()),
                ('value', models.TextField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sub_data', to='core.groupdata')),
            ],
        ),
    ]
