# Generated by Django 5.2.5 on 2025-08-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projectjointoken_delete_projectinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='group_names',
            field=models.TextField(help_text='Tab-separated group names'),
        ),
    ]
